### ISSUE TITLE
LibreWolf browser has broken icon

### ISSUE THREAD

**Issue by tywil04** [sonnyp/Junction#93]
I use the LibreWolf browser as my main browser and its icon is broken in Junction. The application works fine, the icon is just missing. I have LibreWolf installed as a regular application. LibreWolf is a fork of Firefox so I assume it installs similarly to regular Firefox.

The path for the desktop icon is `/usr/share/applications/librewolf.desktop`
The contents of the desktop file is:
```
[Desktop Entry]
Type=Application
Name=LibreWolf
GenericName=Web Browser
# Gnome and KDE 3 uses Comment.
Comment=Web Browser
StartupNotify=true
Terminal=false
Type=Application
MimeType=application/json;application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
Comment=LibreWolf Browser
Categories=Network;WebBrowser;Security;
StartupWMClass=librewolf-default
Exec=/usr/share/librewolf/librewolf %u
Icon=/usr/share/librewolf/browser/chrome/icons/default/default64.png

Actions=new-window;new-private-window;safe-mode;preferences;

[Desktop Action new-window]
Name=New Window
Exec=/usr/share/librewolf/librewolf
[Desktop Action new-private-window]
Name=New Private Window
Exec=/usr/share/librewolf/librewolf --private-window %u
[Desktop Action safe-mode]
Name=Start in Safe Mode
Exec=/usr/share/librewolf/librewolf --safe-mode
[Desktop Action preferences]
Name=Show Preferences
Exec=/usr/share/librewolf/librewolf --preferences
```

I have Brave Browser installed via Flatpak and that works correctly. 

I have attached a video showing the broken icon:
[JunctionLibreWolf.webm](https://user-images.githubusercontent.com/68185249/194785279-51ccff0f-a90a-4ea4-b4be-a954e48831d3.webm)

**Comment by tywil04** [comment]
I just pulled the latest source code, and ran it and the LibreWolf icon shows up correctly. Whatever the issue was it has been fixed, sorry for wasting time.

**Comment by sonnyp** [comment]
I think the issue only appears when sandboxing is enabled. Depend on how you ran Junction from `main` that might not be the case.

It's probably not fixed but is likely to be the same issue as #86

**Comment by tywil04** [comment]
Now that I think of it, I did have Junction installed via flatpak and when I tested from the main branch no form of sandboxing was used so the issue may not have been fixed. Like mentioned originally, LibreWolf is installed without any sandboxing.

I'm happy to provide any details you may want about my system.

**Comment by sonnyp** [comment]
How did you install LibreWolf and what's your OS?

**Comment by tywil04** [comment]
I'm using Fedora 36 as my OS, LibreWolf was installed via the dnf package manager. LibreWolf is a fork of Firefox so I assume it installs similarly.

**Comment by sonnyp** [comment]
LibreWolf isn't available in Fedora reposiory - which of these did you use ? https://librewolf.net/installation/fedora/

Can you try the following:

```
flatpak run --command=sh re.sonny.Junction
du /usr/share/librewolf/browser/chrome/icons/default/default64.png
du /run/host/usr/share/librewolf/browser/chrome/icons/default/default64.png
```

and share the output?

**Comment by tywil04** [comment]
I added the LibreWolf repository to rpm, then used dnf to install the browser (the first option out of the two on the website).

I ran the commands, here are the outputs:
```
du: cannot access '/usr/share/librewolf/browser/chrome/icons/default/default64.png': No such file or directory

4	/run/host/usr/share/librewolf/browser/chrome/icons/default/default64.png
```

**Comment by sonnyp** [comment]
Can you confirm it's fixed in this beta version?

```
flatpak install --user https://dl.flathub.org/build-repo/114055/re.sonny.Junction.flatpakref
flatpak run re.sonny.Junction//test https://example.com
```

**Comment by tywil04** [comment]
It works perfectly! Its all sorted now, thank you.

![Screenshot from 2022-10-14 23-45-44](https://user-images.githubusercontent.com/68185249/195954362-885d3d68-c1aa-483c-82f6-1a3a7b748512.png)
